name = "pintrest-tg-api"
main = "src/index.js" # Double-check if your file is here, e.g., "index.js" or "bot.js"
compatibility_date = "2026-05-16"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# Keep BOT_TOKEN and PINTEREST_COOKIE hidden in your Cloudflare Dashboard settings!
