name = "pintrest-tg-api"
main = "api/index.js"  # Pointing to your actual folder
compatibility_date = "2026-05-16"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# Keep BOT_TOKEN and PINTEREST_COOKIE hidden in your Cloudflare Dashboard settings!
